import { Burst, Code, Manufacturer, Position, Rarity, Weapon, type Nikke } from "./utils";

export const nikkes: Nikke[] = [
    {
        name: "2B",
        image_url: "2BS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Virtuous Rifle",
        squad: "YoRHa",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "A2",
        image_url: "A2S.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Type-40 Blade",
        squad: "YoRHa",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Ade",
        image_url: "AdeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "The Classic",
        squad: "Maid For You",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Admi",
        image_url: "AdmiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Affection's End",
        squad: "Triangle",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Alice",
        image_url: "AliceS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Amazing Wonderland",
        squad: "Unlimited",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Alice: Wonderland Bunny",
        image_url: "Alice_Wonderland_BunnyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "My Little Carrot",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anchor",
        image_url: "AnchorS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Inquisitor",
        squad: "Aegis",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Anis",
        image_url: "AnisS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: "Liberty's Tail",
        squad: "Counters",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anis: Sparkling Summer",
        image_url: "Anis_Sparkling_SummerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Libertine Aqua",
        squad: "Counters",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anne: Miracle Fairy",
        image_url: "Anne_Miracle_FairyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Mayfly",
        squad: "Recall & Release",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Aria",
        image_url: "AriaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Asuka Shikinami Langley",
        image_url: "/Asuka_Shikinami_LangleyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Lightweight Assault Rifle",
        squad: "NERV",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Bay",
        image_url: "BayS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Victory Fanfare",
        squad: "Rewind",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Belorta",
        image_url: "BelortaS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "The Carronades",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Biscuit",
        image_url: "BiscuitS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Happy Puppy",
        squad: "Happy Zoo",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Blanc",
        image_url: "BlancS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "White Pollux",
        squad: "777",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Brid",
        image_url: "BridS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Perfect Line",
        squad: "Infinity Rail",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Centi",
        image_url: "CentiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Mighty Bomber",
        squad: "Mighty Tools",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Clay",
        image_url: "ClayS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "You Can Do It",
        squad: "Rewind",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Cocoa",
        image_url: "CocoaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Cocorella",
        squad: "Maid For You",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Crow",
        image_url: "CrowS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: undefined,
        squad: "Exotic",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Crown",
        image_url: "CrownS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Your Majesty",
        squad: "White Knight",
        code: Code.Iron,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "D",
        image_url: "DS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Storm Eye",
        squad: "Perilous Siege",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "D: Killer Wife",
        image_url: "D_Killer_WifeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Hidden Edge",
        squad: "Perilous Siege",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Delta",
        image_url: "DeltaS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "The Scouts",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Diesel",
        image_url: "DieselS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Wanderlust",
        squad: "Infinity Rail",
        code: Code.Wind,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Dolla",
        image_url: "DollaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "Talentum",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Dorothy",
        image_url: "DorothyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Ungrateful OZ",
        squad: "Inherit",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Drake",
        image_url: "DrakeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Sadistic Carnival",
        squad: "Matis",
        code: Code.Fire,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Ein",
        image_url: "EinS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Young Punk",
        squad: "School Circle",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Elegg",
        image_url: "EleggS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Boomstick",
        squad: "Electric Shock",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Emilia",
        image_url: "EmiliaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Freezing Breath",
        squad: "Emilia's Faction",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Emma",
        image_url: "EmmaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Special Therapy",
        squad: "Absolute",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Epinel",
        image_url: "EpinelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "The Trickster",
        squad: "Nepenthe",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Ether",
        image_url: "EtherS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Sacrificial Bacchanal",
        squad: "M.M.R.",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Eunhwa",
        image_url: "EunhwaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Perfectionist",
        squad: "Absolute",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Exia",
        image_url: "ExiaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Utopia Unsealed",
        squad: "Protocol",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Folkwang",
        image_url: "FolkwangS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Incandescence",
        squad: "Nepenthe",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Frima",
        image_url: "FrimaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Sloth",
        squad: "Cafe Sweety",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Guillotine",
        image_url: "GuillotineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Unbridled Solitude",
        squad: "Extrinsic",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Guilty",
        image_url: "GuiltyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Soft Belt",
        squad: "Real Kindness",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Harran",
        image_url: "HarranS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Death Sentence",
        squad: "Inherit",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Helm",
        image_url: "HelmS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Honorable",
        squad: "Aegis",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Helm: Aquamarine",
        image_url: "Helm_AquamarineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Battleship",
        squad: "Aegis",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Himeno",
        image_url: "HimenoS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: "Ghost Sight",
        squad: "Devil Hunter",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "iDoll Flower",
        image_url: "IDoll_FlowerS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Ocean",
        image_url: "IDoll_OceanS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Sun",
        image_url: "IDoll_SunS.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Isabel",
        image_url: "IsabelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Extreme Obsessor",
        squad: "Inherit",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Jackal",
        image_url: "JackalS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "T.O.P",
        squad: "Exotic",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Julia",
        image_url: "JuliaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Classical Adagio",
        squad: "Master Hand",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Kilo",
        image_url: "KiloS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Anchoret",
        squad: "Heavy Gram",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Laplace",
        image_url: "LaplaceS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Hero Syndrome",
        squad: "Matis",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Leona",
        image_url: "LeonaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Lion's Roar",
        squad: "Happy Zoo",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Liter",
        image_url: "LiterS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Drill Punch",
        squad: "Mighty Tools",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Ludmilla",
        image_url: "LudmillaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Snow Phantom",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Ludmilla: Winter Owner",
        image_url: "Ludmilla_Winter_OwnerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Savior in the Snow",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Maiden",
        image_url: "MaidenS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Misconception",
        squad: "Extrinsic",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Makima",
        image_url: "MakimaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Unknown Weapon",
        squad: "Devil Hunter",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Marciana",
        image_url: "MarcianaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Rational Eyes",
        squad: "Academia",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mari Makinami Illustrious",
        image_url: "/Mari_Makinami_IllustriousS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Long-Range Precision Rifle",
        squad: "NERV",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Mary",
        image_url: "MaryS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Kindness",
        squad: "Seraphim",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mary: Bay Goddess",
        image_url: "Mary_Bay_GoddessS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Summer Shot",
        squad: "Seraphim",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mast",
        image_url: "MastS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Ferocity",
        squad: "Aegis",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Maxwell",
        image_url: "MaxwellS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "My Cutey",
        squad: "Matis",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Mica",
        image_url: "MicaS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "The Carronades",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mica: Snow Buddy",
        image_url: "Mica_Snow_BuddyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Winter Salute",
        squad: "The Carronades",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mihara",
        image_url: "MiharaS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Painful World",
        squad: "Wardress",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Milk",
        image_url: "MilkS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Flawless Victory",
        squad: "Cafe Sweety",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Miranda",
        image_url: "MirandaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Inflexible",
        squad: "A.C.P.U.",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Misato Katsuragi",
        image_url: "/Misato_KatsuragiS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Self-defense Automatic Pistol",
        squad: "NERV",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Modernia",
        image_url: "ModerniaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "New Dawn",
        squad: "Heretic",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Moran",
        image_url: "MoranS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Dragon Head",
        squad: "Underworld Queen",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "N102",
        image_url: "N102S.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Mayfly",
        squad: "Recall & Release",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Naga",
        image_url: "NagaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Elegant Nocturne",
        squad: "Dazzling Pearl",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Neon",
        image_url: "NeonS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Annihilation",
        squad: "Counters",
        code: Code.Fire,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Neon: Blue Ocean",
        image_url: "Neon_Blue_OceanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Big Big Wave",
        squad: "Counters",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Nero",
        image_url: "NeroS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Meow Meow",
        squad: "Happy Zoo",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Neve",
        image_url: "NeveS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Hibernation",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Nihilister",
        image_url: "NihilisterS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "End of the Old World",
        squad: "Heretic",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Noah",
        image_url: "NoahS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Metal Cocoon",
        squad: "Inherit",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Noir",
        image_url: "NoirS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Black Castor",
        squad: "777",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Noise",
        image_url: "NoiseS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Novel",
        image_url: "NovelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Sixth Sense",
        squad: "Protocol",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Pascal",
        image_url: "PascalS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Modified Gun",
        squad: "Machine Lifeform",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Pepper",
        image_url: "PepperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "VitaMax",
        squad: "Seraphim",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Poli",
        image_url: "PoliS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Wild Hound",
        squad: "A.C.P.U.",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Power",
        image_url: "PowerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Powerful Power",
        squad: "Devil Hunter",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Privaty",
        image_url: "PrivatyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Team Chemistry",
        squad: "Triangle",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Privaty: Unkind Maid",
        image_url: "Privaty_Unkind_MaidS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Demanding Lover",
        squad: "Maid For You",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Product 08",
        image_url: "Product_08S.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: "MISR-03",
        squad: "Replace",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 12",
        image_url: "Product_12S.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: "MIMG-07",
        squad: "Replace",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 23",
        image_url: "Product_23S.png",
        rarity: Rarity.R,
        burst: Burst.II,
        weapon_name: "MISG-09",
        squad: "Replace",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Quency",
        image_url: "QuencyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Most Wanted",
        squad: "Real Kindness",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Quiry",
        image_url: "QuiryS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Cloud Eye",
        squad: "A.C.P.U.",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Ram",
        image_url: "RamS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Demon's Gaze",
        squad: "Emilia's Faction",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Rapi",
        image_url: "RapiS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Militaria",
        squad: "Counters",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Rapunzel",
        image_url: "RapunzelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Holy Grace",
        squad: "Pioneer",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Red Hood",
        image_url: "Red_HoodS.png",
        rarity: Rarity.Ssr,
        burst: Burst.A,
        weapon_name: "Wolfsbane",
        squad: "Goddess",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Rei",
        image_url: "ReiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Steel Baby",
        squad: "School Circle",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rei Ayanami",
        image_url: "/Rei_AyanamiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Heavy Gatling Gun for Subdual",
        squad: "NERV",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Rem",
        image_url: "RemS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Demon's Mighty Grip",
        squad: "Emilia's Faction",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Rosanna",
        image_url: "RosannaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Golden Thompson",
        squad: "Underworld Queen",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rosanna: Chic Ocean",
        image_url: "Rosanna_Chic_OceanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Golden Thompson",
        squad: "Underworld Queen",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rupee",
        image_url: "RupeeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Shopaholic",
        squad: "Talentum",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rupee: Winter Shopper",
        image_url: "Rupee_Winter_ShopperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Shopaholic",
        squad: "Talentum",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Sakura",
        image_url: "SakuraS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Ichigenkin",
        squad: "Underworld Queen",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Sakura: Bloom in Summer",
        image_url: "Sakura_Bloom_in_SummerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Ichigenkin",
        squad: "Underworld Queen",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Scarlet",
        image_url: "ScarletS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Fleetly Fading",
        squad: "Pioneer",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Scarlet: Black Shadow",
        image_url: "Scarlet_Black_ShadowS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Fleetly Fading",
        squad: "Goddess",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Signal",
        image_url: "SignalS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Soap Opera",
        squad: "The Scouts",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Sin",
        image_url: "SinS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Heavy Talker",
        squad: "Real Kindness",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Snow White",
        image_url: "Snow_WhiteS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Seven Dwarves",
        squad: "Pioneer",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Snow White: Innocent Days",
        image_url: "Snow_White_Innocent_DaysS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Seven Dwarves II",
        squad: "Goddess",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Soda",
        image_url: "SodaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Bright Cleaner",
        squad: "Maid For You",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Soda: Twinkling Bunny",
        image_url: "Soda_Twinkling_BunnyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Undiminished",
        squad: "Maid For You",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Soldier EG",
        image_url: "Soldier_EGS.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: "Hunting Eagle",
        squad: "Replace",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soldier FA",
        image_url: "Soldier_FAS.png",
        rarity: Rarity.R,
        burst: Burst.II,
        weapon_name: "Clutch Falcon",
        squad: "Replace",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soldier OW",
        image_url: "Soldier_OWS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: "Searching Owl",
        squad: "Replace",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soline",
        image_url: "SolineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Crimson Crusader",
        squad: "Infinity Rail",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Sugar",
        image_url: "SugarS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Cold Zeal",
        squad: "Cafe Sweety",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Tia",
        image_url: "TiaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Chase Nail",
        squad: "Dazzling Pearl",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Tove",
        image_url: "ToveS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Energetic Survivor",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Trony",
        image_url: "TronyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Transistor",
        squad: "Electric Shock",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Vesti",
        image_url: "VestiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Pure Monster",
        squad: "Absolute",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Viper",
        image_url: "ViperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Rust Chaser",
        squad: "Exotic",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Volume",
        image_url: "VolumeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yan",
        image_url: "YanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Talentum",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yulha",
        image_url: "YulhaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Extreme Altruism",
        squad: "Triangle",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yuni",
        image_url: "YuniS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Forbidden Gift",
        squad: "Wardress",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Zwei",
        image_url: "/ZweiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "President Junior",
        squad: "School Circle",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    }
];