import { Burst, Code, Manufacturer, Position, Rarity, Weapon, type Nikke } from "./utils";

export const nikkes: Nikke[] = [
    {
        name: "Rapi",
        image_url: "/images/RapiS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Militaria",
        squad: "Counters",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Neon",
        image_url: "/images/NeonS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Annihilation",
        squad: "Counters",
        code: Code.Fire,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Snow White",
        image_url: "/images/Snow_WhiteS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Seven Dwarves",
        squad: "Pioneer",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Delta",
        image_url: "/images/DeltaS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "The Scouts",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mica",
        image_url: "/images/MicaS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "The Carronades",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Diesel",
        image_url: "/images/DieselS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Wanderlust",
        squad: "Infinity Rail",
        code: Code.Wind,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Miranda",
        image_url: "/images/MirandaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Inflexible",
        squad: "A.C.P.U.",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Emma",
        image_url: "/images/EmmaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Special Therapy",
        squad: "Absolute",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Privaty",
        image_url: "/images/PrivatyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Team Chemistry",
        squad: "Triangle",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Signal",
        image_url: "/images/SignalS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Soap Opera",
        squad: "The Scouts",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Eunhwa",
        image_url: "/images/EunhwaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Perfectionist",
        squad: "Absolute",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Guillotine",
        image_url: "/images/GuillotineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Unbridled Solitude",
        squad: "Extrinsic",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Belorta",
        image_url: "/images/BelortaS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "The Carronades",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Soldier EG",
        image_url: "/images/Soldier_EGS.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: "Hunting Eagle",
        squad: "Replace",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soldier FA",
        image_url: "/images/Soldier_FAS.png",
        rarity: Rarity.R,
        burst: Burst.II,
        weapon_name: "Clutch Falcon",
        squad: "Replace",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soldier OW",
        image_url: "/images/Soldier_OWS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: "Searching Owl",
        squad: "Replace",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Scarlet",
        image_url: "/images/ScarletS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Fleetly Fading",
        squad: "Pioneer",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Noah",
        image_url: "/images/NoahS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Metal Cocoon",
        squad: "Inherit",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Epinel",
        image_url: "/images/EpinelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "The Trickster",
        squad: "Nepenthe",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Exia",
        image_url: "/images/ExiaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Utopia Unsealed",
        squad: "Protocol",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Alice",
        image_url: "/images/AliceS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Amazing Wonderland",
        squad: "Unlimited",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Sugar",
        image_url: "/images/SugarS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Cold Zeal",
        squad: "Cafe Sweety",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Frima",
        image_url: "/images/FrimaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Sloth",
        squad: "Cafe Sweety",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mary",
        image_url: "/images/MaryS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Kindness",
        squad: "Seraphim",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Ludmilla",
        image_url: "/images/LudmillaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Snow Phantom",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anis",
        image_url: "/images/AnisS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: "Liberty's Tail",
        squad: "Counters",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Sun",
        image_url: "/images/IDoll_SunS.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Ocean",
        image_url: "/images/IDoll_OceanS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Flower",
        image_url: "/images/IDoll_FlowerS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Maxwell",
        image_url: "/images/MaxwellS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "My Cutey",
        squad: "Matis",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Yuni",
        image_url: "/images/YuniS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Forbidden Gift",
        squad: "Wardress",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Julia",
        image_url: "/images/JuliaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Classical Adagio",
        squad: "Master Hand",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Drake",
        image_url: "/images/DrakeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Sadistic Carnival",
        squad: "Matis",
        code: Code.Fire,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Mihara",
        image_url: "/images/MiharaS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Painful World",
        squad: "Wardress",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "N102",
        image_url: "/images/N102S.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Mayfly",
        squad: "Recall & Release",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Ether",
        image_url: "/images/EtherS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Sacrificial Bacchanal",
        squad: "M.M.R.",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 08",
        image_url: "/images/Product_08S.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: "MISR-03",
        squad: "Replace",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 12",
        image_url: "/images/Product_12S.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: "MIMG-07",
        squad: "Replace",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 23",
        image_url: "/images/Product_23S.png",
        rarity: Rarity.R,
        burst: Burst.II,
        weapon_name: "MISG-09",
        squad: "Replace",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Centi",
        image_url: "/images/CentiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Mighty Bomber",
        squad: "Mighty Tools",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Soline",
        image_url: "/images/SolineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Crimson Crusader",
        squad: "Infinity Rail",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Helm",
        image_url: "/images/HelmS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Honorable",
        squad: "Aegis",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Volume",
        image_url: "/images/VolumeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Poli",
        image_url: "/images/PoliS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Wild Hound",
        squad: "A.C.P.U.",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Vesti",
        image_url: "/images/VestiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Pure Monster",
        squad: "Absolute",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Laplace",
        image_url: "/images/LaplaceS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Hero Syndrome",
        squad: "Matis",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Dolla",
        image_url: "/images/DollaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "Talentum",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Brid",
        image_url: "/images/BridS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Perfect Line",
        squad: "Infinity Rail",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Crow",
        image_url: "/images/CrowS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: undefined,
        squad: "Exotic",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Harran",
        image_url: "/images/HarranS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Death Sentence",
        squad: "Inherit",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Novel",
        image_url: "/images/NovelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Sixth Sense",
        squad: "Protocol",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yulha",
        image_url: "/images/YulhaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Extreme Altruism",
        squad: "Triangle",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Neve",
        image_url: "/images/NeveS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Hibernation",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Folkwang",
        image_url: "/images/FolkwangS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Incandescence",
        squad: "Nepenthe",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Admi",
        image_url: "/images/AdmiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Affection's End",
        squad: "Triangle",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Maiden",
        image_url: "/images/MaidenS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Misconception",
        squad: "Extrinsic",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Anne: Miracle Fairy",
        image_url: "/images/Anne_Miracle_FairyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Mayfly",
        squad: "Recall & Release",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Rupee",
        image_url: "/images/RupeeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Shopaholic",
        squad: "Talentum",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rupee: Winter Shopper",
        image_url: "/images/Rupee_Winter_ShopperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Shopaholic",
        squad: "Talentum",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rapunzel",
        image_url: "/images/RapunzelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Holy Grace",
        squad: "Pioneer",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Milk",
        image_url: "/images/MilkS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Flawless Victory",
        squad: "Cafe Sweety",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Modernia",
        image_url: "/images/ModerniaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "New Dawn",
        squad: "Heretic",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Isabel",
        image_url: "/images/IsabelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Extreme Obsessor",
        squad: "Inherit",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Noise",
        image_url: "/images/NoiseS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Jackal",
        image_url: "/images/JackalS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "T.O.P",
        squad: "Exotic",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Viper",
        image_url: "/images/ViperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Rust Chaser",
        squad: "Exotic",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yan",
        image_url: "/images/YanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Talentum",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Liter",
        image_url: "/images/LiterS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Drill Punch",
        squad: "Mighty Tools",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Aria",
        image_url: "/images/AriaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Guilty",
        image_url: "/images/GuiltyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Soft Belt",
        squad: "Real Kindness",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Sin",
        image_url: "/images/SinS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Heavy Talker",
        squad: "Real Kindness",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Quency",
        image_url: "/images/QuencyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Most Wanted",
        squad: "Real Kindness",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Pepper",
        image_url: "/images/PepperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "VitaMax",
        squad: "Seraphim",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Cocoa",
        image_url: "/images/CocoaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Cocorella",
        squad: "Maid For You",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Soda",
        image_url: "/images/SodaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Bright Cleaner",
        squad: "Maid For You",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Power",
        image_url: "/images/PowerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Powerful Power",
        squad: "Devil Hunter",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Makima",
        image_url: "/images/MakimaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Unknown Weapon",
        squad: "Devil Hunter",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Himeno",
        image_url: "/images/HimenoS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: "Ghost Sight",
        squad: "Devil Hunter",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Biscuit",
        image_url: "/images/BiscuitS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Happy Puppy",
        squad: "Happy Zoo",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Nihilister",
        image_url: "/images/NihilisterS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "End of the Old World",
        squad: "Heretic",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Ade",
        image_url: "/images/AdeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "The Classic",
        squad: "Maid For You",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Sakura",
        image_url: "/images/SakuraS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Ichigenkin",
        squad: "Underworld Queen",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "D",
        image_url: "/images/DS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Storm Eye",
        squad: "Perilous Siege",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Moran",
        image_url: "/images/MoranS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Dragon Head",
        squad: "Underworld Queen",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rosanna",
        image_url: "/images/RosannaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Golden Thompson",
        squad: "Underworld Queen",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Dorothy",
        image_url: "/images/DorothyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Ungrateful OZ",
        squad: "Inherit",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Rei",
        image_url: "/images/ReiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Steel Baby",
        squad: "School Circle",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anchor",
        image_url: "/images/AnchorS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Inquisitor",
        squad: "Aegis",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mast",
        image_url: "/images/MastS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Ferocity",
        squad: "Aegis",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Nero",
        image_url: "/images/NeroS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Meow Meow",
        squad: "Happy Zoo",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Red Hood",
        image_url: "/images/Red_HoodS.png",
        rarity: Rarity.Ssr,
        burst: Burst.A,
        weapon_name: "Wolfsbane",
        squad: "Goddess",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Blanc",
        image_url: "/images/BlancS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "White Pollux",
        squad: "777",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Noir",
        image_url: "/images/NoirS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Black Castor",
        squad: "777",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mary: Bay Goddess",
        image_url: "/images/Mary_Bay_GoddessS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Summer Shot",
        squad: "Seraphim",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Neon: Blue Ocean",
        image_url: "/images/Neon_Blue_OceanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Big Big Wave",
        squad: "Counters",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Leona",
        image_url: "/images/LeonaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Lion's Roar",
        squad: "Happy Zoo",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anis: Sparkling Summer",
        image_url: "/images/Anis_Sparkling_SummerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Libertine Aqua",
        squad: "Counters",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Helm: Aquamarine",
        image_url: "/images/Helm_AquamarineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Battleship",
        squad: "Aegis",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Crown",
        image_url: "/images/CrownS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Your Majesty",
        squad: "White Knight",
        code: Code.Iron,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "2B",
        image_url: "/images/2BS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Virtuous Rifle",
        squad: "YoRHa",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "A2",
        image_url: "/images/A2S.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Type-40 Blade",
        squad: "YoRHa",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Pascal",
        image_url: "/images/PascalS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Modified Gun",
        squad: "Machine Lifeform",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Marciana",
        image_url: "/images/MarcianaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Rational Eyes",
        squad: "Academia",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Naga",
        image_url: "/images/NagaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Elegant Nocturne",
        squad: "Dazzling Pearl",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Tia",
        image_url: "/images/TiaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Chase Nail",
        squad: "Dazzling Pearl",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Quiry",
        image_url: "/images/QuiryS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Cloud Eye",
        squad: "A.C.P.U.",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Snow White: Innocent Days",
        image_url: "/images/Snow_White_Innocent_DaysS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Seven Dwarves II",
        squad: "Goddess",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Tove",
        image_url: "/images/ToveS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Energetic Survivor",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Ludmilla: Winter Owner",
        image_url: "/images/Ludmilla_Winter_OwnerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Savior in the Snow",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mica: Snow Buddy",
        image_url: "/images/Mica_Snow_BuddyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Winter Salute",
        squad: "The Carronades",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Scarlet: Black Shadow",
        image_url: "/images/Scarlet_Black_ShadowS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Fleetly Fading",
        squad: "Goddess",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Privaty: Unkind Maid",
        image_url: "/images/Privaty_Unkind_MaidS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Demanding Lover",
        squad: "Maid For You",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Elegg",
        image_url: "/images/EleggS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Boomstick",
        squad: "Electric Shock",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Trony",
        image_url: "/images/TronyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Transistor",
        squad: "Electric Shock",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "D: Killer Wife",
        image_url: "/images/D_Killer_WifeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Hidden Edge",
        squad: "Perilous Siege",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Emilia",
        image_url: "/images/EmiliaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Freezing Breath",
        squad: "Emilia's Faction",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Rem",
        image_url: "/images/RemS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Demon's Mighty Grip",
        squad: "Emilia's Faction",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Ram",
        image_url: "/images/RamS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Demon's Gaze",
        squad: "Emilia's Faction",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Bay",
        image_url: "/images/BayS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Victory Fanfare",
        squad: "Rewind",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Kilo",
        image_url: "/images/KiloS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Anchoret",
        squad: "Heavy Gram",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Soda: Twinkling Bunny",
        image_url: "/images/Soda_Twinkling_BunnyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Undiminished",
        squad: "Maid For You",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Alice: Wonderland Bunny",
        image_url: "/images/Alice_Wonderland_BunnyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "My Little Carrot",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rapi",
        image_url: "/images/RapiS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Militaria",
        squad: "Counters",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Neon",
        image_url: "/images/NeonS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Annihilation",
        squad: "Counters",
        code: Code.Fire,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Snow White",
        image_url: "/images/Snow_WhiteS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Seven Dwarves",
        squad: "Pioneer",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Delta",
        image_url: "/images/DeltaS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "The Scouts",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mica",
        image_url: "/images/MicaS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "The Carronades",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Diesel",
        image_url: "/images/DieselS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Wanderlust",
        squad: "Infinity Rail",
        code: Code.Wind,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Miranda",
        image_url: "/images/MirandaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Inflexible",
        squad: "A.C.P.U.",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Emma",
        image_url: "/images/EmmaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Special Therapy",
        squad: "Absolute",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Privaty",
        image_url: "/images/PrivatyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Team Chemistry",
        squad: "Triangle",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Signal",
        image_url: "/images/SignalS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Soap Opera",
        squad: "The Scouts",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Eunhwa",
        image_url: "/images/EunhwaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Perfectionist",
        squad: "Absolute",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Guillotine",
        image_url: "/images/GuillotineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Unbridled Solitude",
        squad: "Extrinsic",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Belorta",
        image_url: "/images/BelortaS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "The Carronades",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Soldier EG",
        image_url: "/images/Soldier_EGS.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: "Hunting Eagle",
        squad: "Replace",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soldier FA",
        image_url: "/images/Soldier_FAS.png",
        rarity: Rarity.R,
        burst: Burst.II,
        weapon_name: "Clutch Falcon",
        squad: "Replace",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Soldier OW",
        image_url: "/images/Soldier_OWS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: "Searching Owl",
        squad: "Replace",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Scarlet",
        image_url: "/images/ScarletS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Fleetly Fading",
        squad: "Pioneer",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Noah",
        image_url: "/images/NoahS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Metal Cocoon",
        squad: "Inherit",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Epinel",
        image_url: "/images/EpinelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "The Trickster",
        squad: "Nepenthe",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Exia",
        image_url: "/images/ExiaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Utopia Unsealed",
        squad: "Protocol",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Alice",
        image_url: "/images/AliceS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Amazing Wonderland",
        squad: "Unlimited",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Sugar",
        image_url: "/images/SugarS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Cold Zeal",
        squad: "Cafe Sweety",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Frima",
        image_url: "/images/FrimaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Sloth",
        squad: "Cafe Sweety",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Mary",
        image_url: "/images/MaryS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Kindness",
        squad: "Seraphim",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Ludmilla",
        image_url: "/images/LudmillaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Snow Phantom",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anis",
        image_url: "/images/AnisS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: "Liberty's Tail",
        squad: "Counters",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Sun",
        image_url: "/images/IDoll_SunS.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Ocean",
        image_url: "/images/IDoll_OceanS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "iDoll Flower",
        image_url: "/images/IDoll_FlowerS.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Replace",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yuni",
        image_url: "/images/YuniS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Forbidden Gift",
        squad: "Wardress",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Maxwell",
        image_url: "/images/MaxwellS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "My Cutey",
        squad: "Matis",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Julia",
        image_url: "/images/JuliaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Classical Adagio",
        squad: "Master Hand",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Drake",
        image_url: "/images/DrakeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Sadistic Carnival",
        squad: "Matis",
        code: Code.Fire,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Mihara",
        image_url: "/images/MiharaS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Painful World",
        squad: "Wardress",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "N102",
        image_url: "/images/N102S.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Mayfly",
        squad: "Recall & Release",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Ether",
        image_url: "/images/EtherS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Sacrificial Bacchanal",
        squad: "M.M.R.",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 08",
        image_url: "/images/Product_08S.png",
        rarity: Rarity.R,
        burst: Burst.I,
        weapon_name: "MISR-03",
        squad: "Replace",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 12",
        image_url: "/images/Product_12S.png",
        rarity: Rarity.R,
        burst: Burst.III,
        weapon_name: "MIMG-07",
        squad: "Replace",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Product 23",
        image_url: "/images/Product_23S.png",
        rarity: Rarity.R,
        burst: Burst.II,
        weapon_name: "MISG-09",
        squad: "Replace",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Centi",
        image_url: "/images/CentiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Mighty Bomber",
        squad: "Mighty Tools",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Soline",
        image_url: "/images/SolineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Crimson Crusader",
        squad: "Infinity Rail",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Helm",
        image_url: "/images/HelmS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Honorable",
        squad: "Aegis",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Volume",
        image_url: "/images/VolumeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Poli",
        image_url: "/images/PoliS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Wild Hound",
        squad: "A.C.P.U.",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Vesti",
        image_url: "/images/VestiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Pure Monster",
        squad: "Absolute",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Laplace",
        image_url: "/images/LaplaceS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Hero Syndrome",
        squad: "Matis",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Dolla",
        image_url: "/images/DollaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "Talentum",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Brid",
        image_url: "/images/BridS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Perfect Line",
        squad: "Infinity Rail",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Crow",
        image_url: "/images/CrowS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: undefined,
        squad: "Exotic",
        code: Code.Fire,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Harran",
        image_url: "/images/HarranS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Death Sentence",
        squad: "Inherit",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Novel",
        image_url: "/images/NovelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Sixth Sense",
        squad: "Protocol",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yulha",
        image_url: "/images/YulhaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Extreme Altruism",
        squad: "Triangle",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Neve",
        image_url: "/images/NeveS.png",
        rarity: Rarity.Sr,
        burst: Burst.III,
        weapon_name: "Hibernation",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Folkwang",
        image_url: "/images/FolkwangS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Incandescence",
        squad: "Nepenthe",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Admi",
        image_url: "/images/AdmiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Affection's End",
        squad: "Triangle",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Maiden",
        image_url: "/images/MaidenS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Misconception",
        squad: "Extrinsic",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Anne: Miracle Fairy",
        image_url: "/images/Anne_Miracle_FairyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Mayfly",
        squad: "Recall & Release",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Rupee",
        image_url: "/images/RupeeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Shopaholic",
        squad: "Talentum",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rupee: Winter Shopper",
        image_url: "/images/Rupee_Winter_ShopperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Shopaholic",
        squad: "Talentum",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Milk",
        image_url: "/images/MilkS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Flawless Victory",
        squad: "Cafe Sweety",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rapunzel",
        image_url: "/images/RapunzelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Holy Grace",
        squad: "Pioneer",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Modernia",
        image_url: "/images/ModerniaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "New Dawn",
        squad: "Heretic",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Isabel",
        image_url: "/images/IsabelS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Extreme Obsessor",
        squad: "Inherit",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Noise",
        image_url: "/images/NoiseS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Jackal",
        image_url: "/images/JackalS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "T.O.P",
        squad: "Exotic",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Viper",
        image_url: "/images/ViperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Rust Chaser",
        squad: "Exotic",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Yan",
        image_url: "/images/YanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: undefined,
        squad: "Talentum",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Liter",
        image_url: "/images/LiterS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Drill Punch",
        squad: "Mighty Tools",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Aria",
        image_url: "/images/AriaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: undefined,
        squad: "Prima Donna",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Guilty",
        image_url: "/images/GuiltyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Soft Belt",
        squad: "Real Kindness",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Sin",
        image_url: "/images/SinS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Heavy Talker",
        squad: "Real Kindness",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Quency",
        image_url: "/images/QuencyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Most Wanted",
        squad: "Real Kindness",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Pepper",
        image_url: "/images/PepperS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "VitaMax",
        squad: "Seraphim",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Cocoa",
        image_url: "/images/CocoaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Cocorella",
        squad: "Maid For You",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Soda",
        image_url: "/images/SodaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Bright Cleaner",
        squad: "Maid For You",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Power",
        image_url: "/images/PowerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Powerful Power",
        squad: "Devil Hunter",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Makima",
        image_url: "/images/MakimaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Unknown Weapon",
        squad: "Devil Hunter",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Himeno",
        image_url: "/images/HimenoS.png",
        rarity: Rarity.Sr,
        burst: Burst.II,
        weapon_name: "Ghost Sight",
        squad: "Devil Hunter",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Biscuit",
        image_url: "/images/BiscuitS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Happy Puppy",
        squad: "Happy Zoo",
        code: Code.Electric,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Nihilister",
        image_url: "/images/NihilisterS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "End of the Old World",
        squad: "Heretic",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Sakura",
        image_url: "/images/SakuraS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Ichigenkin",
        squad: "Underworld Queen",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "D",
        image_url: "/images/DS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Storm Eye",
        squad: "Perilous Siege",
        code: Code.Wind,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Rosanna",
        image_url: "/images/RosannaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Golden Thompson",
        squad: "Underworld Queen",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Dorothy",
        image_url: "/images/DorothyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Ungrateful OZ",
        squad: "Inherit",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Rei",
        image_url: "/images/ReiS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Steel Baby",
        squad: "School Circle",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anchor",
        image_url: "/images/AnchorS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Inquisitor",
        squad: "Aegis",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mast",
        image_url: "/images/MastS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Ferocity",
        squad: "Aegis",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Nero",
        image_url: "/images/NeroS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Meow Meow",
        squad: "Happy Zoo",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Red Hood",
        image_url: "/images/Red_HoodS.png",
        rarity: Rarity.Ssr,
        burst: Burst.A,
        weapon_name: "Wolfsbane",
        squad: "Goddess",
        code: Code.Iron,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Blanc",
        image_url: "/images/BlancS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "White Pollux",
        squad: "777",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Noir",
        image_url: "/images/NoirS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Black Castor",
        squad: "777",
        code: Code.Wind,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Helm: Aquamarine",
        image_url: "/images/Helm_AquamarineS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Battleship",
        squad: "Aegis",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mary: Bay Goddess",
        image_url: "/images/Mary_Bay_GoddessS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Summer Shot",
        squad: "Seraphim",
        code: Code.Water,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Anis: Sparkling Summer",
        image_url: "/images/Anis_Sparkling_SummerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Libertine Aqua",
        squad: "Counters",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "2B",
        image_url: "/images/2BS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Virtuous Rifle",
        squad: "YoRHa",
        code: Code.Fire,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "A2",
        image_url: "/images/A2S.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Type-40 Blade",
        squad: "YoRHa",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Pascal",
        image_url: "/images/PascalS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Modified Gun",
        squad: "Machine Lifeform",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Marciana",
        image_url: "/images/MarcianaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Rational Eyes",
        squad: "Academia",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Naga",
        image_url: "/images/NagaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Elegant Nocturne",
        squad: "Dazzling Pearl",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Tia",
        image_url: "/images/TiaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Chase Nail",
        squad: "Dazzling Pearl",
        code: Code.Iron,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Quiry",
        image_url: "/images/QuiryS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Cloud Eye",
        squad: "A.C.P.U.",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Snow White: Innocent Days",
        image_url: "/images/Snow_White_Innocent_DaysS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Seven Dwarves II",
        squad: "Goddess",
        code: Code.Iron,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Neon: Blue Ocean",
        image_url: "/images/Neon_Blue_OceanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Big Big Wave",
        squad: "Counters",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Mica: Snow Buddy",
        image_url: "/images/Mica_Snow_BuddyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Winter Salute",
        squad: "The Carronades",
        code: Code.Iron,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Ludmilla: Winter Owner",
        image_url: "/images/Ludmilla_Winter_OwnerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Savior in the Snow",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Tove",
        image_url: "/images/ToveS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Energetic Survivor",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Scarlet: Black Shadow",
        image_url: "/images/Scarlet_Black_ShadowS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Fleetly Fading",
        squad: "Goddess",
        code: Code.Wind,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Leona",
        image_url: "/images/LeonaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Lion's Roar",
        squad: "Happy Zoo",
        code: Code.Water,
        weapon_type: Weapon.Shotgun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Moran",
        image_url: "/images/MoranS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Dragon Head",
        squad: "Underworld Queen",
        code: Code.Electric,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Privaty: Unkind Maid",
        image_url: "/images/Privaty_Unkind_MaidS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Demanding Lover",
        squad: "Maid For You",
        code: Code.Electric,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Ade",
        image_url: "/images/AdeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "The Classic",
        squad: "Maid For You",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Elegg",
        image_url: "/images/EleggS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Boomstick",
        squad: "Electric Shock",
        code: Code.Electric,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "D: Killer Wife",
        image_url: "/images/D_Killer_WifeS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "Hidden Edge",
        squad: "Perilous Siege",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Elysion,
    },
    {
        name: "Emilia",
        image_url: "/images/EmiliaS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Freezing Breath",
        squad: "Emilia's Faction",
        code: Code.Water,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Attacker,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Rem",
        image_url: "/images/RemS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Demon's Mighty Grip",
        squad: "Emilia's Faction",
        code: Code.Water,
        weapon_type: Weapon.MachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Ram",
        image_url: "/images/RamS.png",
        rarity: Rarity.Sr,
        burst: Burst.I,
        weapon_name: "Demon's Gaze",
        squad: "Emilia's Faction",
        code: Code.Wind,
        weapon_type: Weapon.SniperRifle,
        position: Position.Defender,
        manufacturer: Manufacturer.Abnormal,
    },
    {
        name: "Bay",
        image_url: "/images/BayS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Victory Fanfare",
        squad: "Rewind",
        code: Code.Fire,
        weapon_type: Weapon.RocketLauncher,
        position: Position.Defender,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Crown",
        image_url: "/images/CrownS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Your Majesty",
        squad: "White Knight",
        code: Code.Iron,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Pilgrim,
    },
    {
        name: "Kilo",
        image_url: "/images/KiloS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Anchoret",
        squad: "Heavy Gram",
        code: Code.Fire,
        weapon_type: Weapon.MachineGun,
        position: Position.Defender,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Trony",
        image_url: "/images/TronyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Transistor",
        squad: "Electric Shock",
        code: Code.Fire,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    },
    {
        name: "Soda: Twinkling Bunny",
        image_url: "/images/Soda_Twinkling_BunnyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Undiminished",
        squad: "Maid For You",
        code: Code.Iron,
        weapon_type: Weapon.Shotgun,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Alice: Wonderland Bunny",
        image_url: "/images/Alice_Wonderland_BunnyS.png",
        rarity: Rarity.Ssr,
        burst: Burst.I,
        weapon_name: "My Little Carrot",
        squad: "Unlimited",
        code: Code.Water,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Clay",
        image_url: "/images/ClayS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "You Can Do It",
        squad: "Rewind",
        code: Code.Electric,
        weapon_type: Weapon.SubmachineGun,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Rosanna: Chic Ocean",
        image_url: "/images/Rosanna_Chic_OceanS.png",
        rarity: Rarity.Ssr,
        burst: Burst.II,
        weapon_name: "Golden Thompson",
        squad: "Underworld Queen",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Supporter,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Sakura: Bloom in Summer",
        image_url: "/images/Sakura_Bloom_in_SummerS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Ichigenkin",
        squad: "Underworld Queen",
        code: Code.Wind,
        weapon_type: Weapon.AssaultRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Tetra,
    },
    {
        name: "Ein",
        image_url: "/images/EinS.png",
        rarity: Rarity.Ssr,
        burst: Burst.III,
        weapon_name: "Young Punk",
        squad: "School Circle",
        code: Code.Electric,
        weapon_type: Weapon.SniperRifle,
        position: Position.Attacker,
        manufacturer: Manufacturer.Missilis,
    }
];